name: Continuos Integration

on:
  push:  
    branches: 
      [main]
    

jobs: 
  continuos-integration: 
    runs-on: ubuntu-latest

    # Caso algum desses passos falhe, o workflow todo vai falhar. 
    steps:
      - name: Download da Branch na máquina virtual
        uses: actions/checkout@v3 ##Copia os arquivos do repositório para dentro da máquina criada
      
      - name: Usar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Instalar Dependências
        run: npm install

      # - name: Rodar testes
      #   run: npm run test

      # - name: Buildar Projeto
      #   run: npm run build


      