name: Continuos Integration

on:
  pull_request:  
    branches: 
      [main]
    types: 
      [closed]
    

jobs: 
  continuos-integration: 
    runs-on: ubuntu-latest

    # Caso algum desses passos falhe, o workflow todo vai falhar. 
    steps:
      - name: Download Branch in virtual machine
        uses: actions/checkout@v3
      
      - name: Usar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Instalar Dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      # - name: Buildar Projeto
      #   run: npm run build


      